Repository briandidierjean/projet7-da-php-symfony-oc, pull requests merged in 2021-07, with the labels that each got.

#10 Model
  .dockerignore
  src/Entity/Customer.php
  src/Entity/Product.php
  src/Entity/ProductCategory.php
  src/Entity/User.php
  uml/Classes Diagram.png
Labels: core

#11 Endpoints
  composer.json
  composer.lock
  config/bundles.php
  config/packages/fos_rest.yaml
  config/packages/sensio_framework_extra.yaml
  src/Controller/ProductController.php
  src/DataFixtures/ProductCategoryFixtures.php
  src/DataFixtures/ProductFixtures.php
  src/Entity/Product.php
  src/Entity/ProductCategory.php
  src/Repository/AbstractRepository.php
  src/Repository/ProductRepository.php
  src/Representation/Products.php
  symfony.lock
Labels: core

#12 Add Consulting the BileMo product details endpoint
  src/Controller/ProductController.php
  src/Entity/Product.php
  src/Entity/ProductCategory.php
  src/Representation/Products.php
Labels: core

#14 Add Consulting the user details owned by a customer endpoint
  src/Controller/UserController.php
  src/Entity/Customer.php
  src/Entity/User.php
Labels: core

#15 Endpoints
  config/packages/fos_rest.yaml
  src/Controller/UserController.php
  src/Entity/Customer.php
  src/Entity/User.php
  src/Exception/ResourceValidationException.php
Labels: core

#16 Add 'Removing a user added by a customer' endpoint
  config/packages/fos_rest.yaml
  src/Controller/UserController.php
Labels: core

#18 Add Hypermedia controls
  composer.json
  composer.lock
  config/bundles.php
  config/packages/bazinga_hateoas.yaml
  src/Entity/Product.php
  src/Entity/User.php
  symfony.lock
Labels: core

#19 Authentication
  config/packages/fos_rest.yaml
  config/packages/lexik_jwt_authentication.yaml
  config/packages/security.yaml
  config/routes.yaml
  src/Controller/UserController.php
  src/DataFixtures/CustomerFixtures.php
  src/Entity/Customer.php
  src/Entity/Product.php
  src/Entity/ProductCategory.php
  src/Entity/User.php
  src/Exception/ForbiddenException.php
  src/Exception/ResourceValidationException.php
  src/Representation/Products.php
  src/Representation/Users.php
Labels: core

#20 Documentation
  composer.json
  composer.lock
  config/bundles.php
  config/packages/fos_rest.yaml
  config/packages/nelmio_api_doc.yaml
  config/packages/security.yaml
  config/routes/nelmio_api_doc.yaml
  src/Controller/ProductController.php
  src/Controller/UserController.php
  src/DataFixtures/CustomerFixtures.php
  src/DataFixtures/UserFixtures.php
  symfony.lock
Labels: documentation

#25 Representation criteria
  docker-compose.yml
  src/Controller/ProductController.php
  src/Controller/UserController.php
  src/DataFixtures/CustomerFixtures.php
  src/DataFixtures/ProductFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Repository/ProductRepository.php
  src/Repository/UserRepository.php
  src/Representation/Products.php
  src/Representation/Users.php
Labels: enhancement

#29 Add a Codacy badge to README.md
  README.md
Labels: documentation
